#!/usr/bin/env bash
# Configuring the Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Hello World!' > /var/www/html/index.html
sed -i '/^\tserver_name.*/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start
sudo service nginx reload
