#!/usr/bin/env bash
# Configuring the Nginx server that have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

SERVER_CONFIG=\
"server {
        listen 80;
        listen [::]:80;
        root /var/www/your_domain/html;
        index index.html index.htm index.nginx-debian.html;
        server_name ubuntu_44.192.253.90 www.ubuntu_44.192.253.90;
        location / {
                try_files $uri $uri/ =404;
        }
        
        if (\$request_filename ~ redirect_me){
		rewrite ^ https://sketchfab.com/bluepeno/models permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		root /var/www/error/;
		internal;
	}
}
"
echo "Ceci n'est pas une page" > /var/www/html/404.html

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ];
then
	service nginx start
else
	service nginx restart
fi;
