#!/usr/bin/env bash
# Configuring the Nginx server that have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html

SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /404.html;
        location  /404.html {
            internal;
        }
        
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.holbertonschool.com/watch?v=QH2-TGUlwu4 permanent;
}
}
"
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ];
then
	service nginx start
else
	service nginx restart
fi;
