#!/usr/bin/env bash
# Install nginx and add a custom header
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed 's/http {/&\n\tadd_header X-Served-By $HOSTNAME/' /etc/nginx/nginx.conf
sudo service nginx restart
