#!/usr/bin/env bash
# Install haproxy and config 2 server
sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*
echo -e '
frontend http-in
\tmode http
\tbind *:80
\tdefault_backend web_servers
backend web_servers
\tbalance roundrobin
\tserver 20549-web-01 3.239.58.144:80 check
\tserver 20549-web-02 100.24.126.136:80 check
' >> /etc/haproxy/haproxy.cfg 
echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
