#!/usr/bin/env bash
# Install haproxy and config 2 server
sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sudo sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 20549-web-01 44.192.253.90:80 check\n\tserver 20549-web-2 3.234.240.79:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
