#!/usr/bin/env bash
# Displays all acive IPv4 addresses on the machine.

# a different way using ifconfig but now ip is a new command and ifconfig can be missing in some os
#ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'

ip=$(ip address| awk '/inet/ {print $2}' | grep -v ^::1 | grep -v ^127)
